### ISSUE TITLE
No config or documentation

### ISSUE THREAD

**Issue by ghost** [Innoz-Technologies/SMSGyan#2]
Hi,

I am trying to explore how this works but there's no proper documentation or any configuration to make it working, so i am unable to figure it out, even there is no proper directory structure and the code is not orgnized. So if there's some documentation available and some tips about the configuration, then it will be really helpful.

Thanks and Regards
Ashish

**Comment by mevinbabuc** [comment]
I don't think this is the full source code of the project. It's just some of the API libraries they wrote to crawl/fetch results from other sources.
